"""empty message

Revision ID: ef8841582aa1
Revises: b549b198de79
Create Date: 2022-03-22 00:01:37.284323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef8841582aa1'
down_revision = 'b549b198de79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('end_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'end_time')
    # ### end Alembic commands ###
